# Generated by Django 4.2.8 on 2023-12-10 21:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('outdoorbuddies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adventure',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_adventures', to=settings.AUTH_USER_MODEL),
        ),
    ]
