# Generated by Django 4.2.8 on 2023-12-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outdoorbuddies', '0002_adventure_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adventure',
            name='status',
        ),
        migrations.RemoveField(
            model_name='adventureparticipants',
            name='status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='interests',
            field=models.ManyToManyField(blank=True, to='outdoorbuddies.tag'),
        ),
    ]
